Eval:
  gt_root: "D:/datasets/polyp/TestDataset"
  pred_root: "./result_map/MVSNet"
  result_path: "./results/MVSNet"
  datasets: [ 'CVC-300', 'CVC-ClinicDB', 'Kvasir', 'CVC-ColonDB', 'ETIS-LaribPolypDB', 'test']
  metrics: [ 'meanDic', 'meanIoU', 'wFm', 'Sm', 'meanEm', 'mae', 'maxEm', 'maxDic', 'maxIoU', 'meanSen', 'maxSen', 'meanSpe', 'maxSpe' ]